-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.articles;

CREATE TABLE IF NOT EXISTS public.articles
(
    id serial NOT NULL,
    message text NOT NULL,
    create_at date DEFAULT CURRENT_DATE,
    delete_at date DEFAULT CURRENT_DATE,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.commentaires;

CREATE TABLE IF NOT EXISTS public.commentaires
(
    id serial NOT NULL,
    commentaire text NOT NULL,
    create_at date DEFAULT CURRENT_DATE,
    delete_at date DEFAULT CURRENT_DATE,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.articles
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.commentaires
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.commentaires
    ADD FOREIGN KEY (id)
    REFERENCES public.articles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;